import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import categoriesRouter from "./categories";
import itemsRouter from "./items";
import receiptsRouter from "./receipts";
import writeOffsRouter from "./writeOffs";
import inventoryAuditsRouter from "./inventoryAudits";
import staffRouter from "./staff";
import analyticsRouter from "./analytics";
import auditLogRouter from "./auditLog";
import exportRouter from "./exportRoutes";
import storageRouter from "./storage";
import rentalsRouter from "./rentals";
import onboardingRouter from "./onboarding";
import settingsRouter from "./settings";
import locationsRouter from "./locations";
import transfersRouter from "./transfers";
import userLocationsRouter from "./userLocations";
import housesRouter from "./houses";
import registersRouter from "./registers";
import shiftsRouter from "./shifts";
import salesRouter from "./sales";
import kassaAnalyticsRouter from "./kassaAnalytics";
import devSeedRouter from "./devSeed";
import productsRouter from "./products";
import productRecipesRouter from "./productRecipes";
import cashMovementsRouter from "./cashMovements";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(onboardingRouter);
router.use(locationsRouter);
router.use(transfersRouter);
router.use(userLocationsRouter);
router.use(housesRouter);
router.use(registersRouter);
router.use(shiftsRouter);
router.use(salesRouter);
router.use(kassaAnalyticsRouter);
router.use(devSeedRouter);
router.use(productsRouter);
router.use(productRecipesRouter);
router.use(cashMovementsRouter);
router.use(categoriesRouter);
router.use(itemsRouter);
router.use(receiptsRouter);
router.use(writeOffsRouter);
router.use(inventoryAuditsRouter);
router.use(staffRouter);
router.use(analyticsRouter);
router.use(auditLogRouter);
router.use(exportRouter);
router.use(storageRouter);
router.use(rentalsRouter);
router.use(settingsRouter);

export default router;
